# Generated by Django 3.0.8 on 2020-07-31 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ServiceProvider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=11)),
                ('descriptionProblem', models.TextField(max_length=100)),
                ('applyAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RenameField(
            model_name='servicprovider',
            old_name='descraption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='servicprovider',
            old_name='Fname',
            new_name='jopType',
        ),
        migrations.RenameField(
            model_name='servicprovider',
            old_name='publish_at',
            new_name='publishAt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.RemoveField(
            model_name='servicprovider',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='servicprovider',
            name='jop_type',
        ),
        migrations.AddField(
            model_name='servicprovider',
            name='Vacancy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicprovider',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyService', to='ServiceProvider.ServicProvider'),
        ),
    ]
