# Generated by Django 3.0.8 on 2020-07-31 11:53

import ServiceProvider.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0002_auto_20200731_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicprovider',
            name='img',
            field=models.ImageField(default=1, upload_to=ServiceProvider.models.image_upload),
            preserve_default=False,
        ),
    ]
