# Generated by Django 3.0.8 on 2020-08-03 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceProvider', '0004_auto_20200803_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicprovider',
            name='cityUser',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
