# Generated by Django 3.0.8 on 2020-08-08 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200806_0519'),
        ('ServiceProvider', '0005_auto_20200803_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('servicProvider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ServiceProvider.ServicProvider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Profile')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
